### ISSUE TITLE
Service definition disabled if not collecting debug data

### ISSUE THREAD

**Issue by elernonelma** [egeloen/IvoryHttpAdapterBundle#7]
I encounter the problem when I use in my app the "--no-debug" option of "cache:clear" command:

    php app/console cache:clear --no-debug

Current output:

    Clearing the cache for the dev environment with debug false
    [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]            
    The service definition "ivory.http_adapter.default.event_dispatcher" does not exist. 

I just downloaded a fresh symfony2 distrib to reproduce it. I just added the bundle & added this service definition:

    services:
        service_name:
            class: AppBundle\Directory\ClassName
            tags:
                -
                    name: ivory.http_adapter.subscriber

**Comment by elernonelma** [comment]
I will try to look for the reason asap.

**Comment by egeloen** [comment]
For now, this is the expected behavior. Basically, the services are builded via the DI extension. Then, at this state, I can't know you will want to use events (via service tags) and so don't build an event dispatcher http adapter decorator for your adapter. The only way I see to make it automatic is to move the decorators creation (event dispatcher + stopwatch) in the compiler pass (the only place I can detect your tagged services).

For now, the way to force the usage of the event dispatcher http adapter decorator is to put the following in your config:

``` yaml
ivory_http_adapter:
    subscribers: true
```

Then, all builded adapters will use an event dispatcher decorator.

**Comment by elernonelma** [comment]
I see, thanks for the explanations :+1: 
Works like a charm => I close it.
